server:
  port: 8761

eureka:
  instance:
    hostname: localhost         #Tells Eureka what host it's running on. If not specified Eureka will attempt to determine its host from environment variables
  client:
    registerWithEureka: false   #Eureka by default will register itself as a client of other Eureka services. So, we need to set it to false.
    fetchRegistry: false        #Indicates whether this client should fetch eureka registry information from other eureka server.
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"